### ISSUE TITLE
Disable Update Check

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-action-setup#78]
**Context**
Speaking with @e-gineer raised a question about whether or not we should be disabling the update check via the [STEAMPIPE_UPDATE_CHECK](https://steampipe.io/docs/reference/env-vars/steampipe_update_check#steampipe_update_check) env var.

Doing so would create a performance optimisation as it wouldn't need to "call-home" to check if there are updates, since we install latest unless a specific version is set in the `with` section using `steampipe-version: {version}` it doesn't make sense to check.

**Comment by cbruno10** [comment]
We can also disable update checks with the [update_check option](https://steampipe.io/docs/reference/config-files/options#general-options). Not sure if this is better than the env var, but we could update the `default.spc` to have this option set.
